name: Auto Label

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels based on changed files
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
